version: "3"

vars:
  PORT: "3000"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  dev:
    desc: Run Next.js local development server
    cmds:
      - npm run dev

  test:
    desc: Run Jest unit tests
    cmds:
      - npm run test